bundler_args: ""
language: ruby
gemfile:
  - spec/gemfiles/32.gemfile
  - spec/gemfiles/40.gemfile
  - spec/gemfiles/41.gemfile
  - spec/gemfiles/42.gemfile
  - spec/gemfiles/50.gemfile
rvm:
  - 2.0
  - 2.1
  - 2.2
matrix:
  exclude:
script: bundle exec rake spec

addons:
  postgresql: "9.3"

services:
  - redis-server

before_install:
  - gem update bundler

before_script:
  - psql -c 'create database "inst-jobs-test-1";' -U postgres

env:
  - TEST_DB_USERNAME=postgres
