language: ruby
gemfile:
  - spec/gemfiles/42.gemfile
  - spec/gemfiles/50.gemfile
  - spec/gemfiles/51.gemfile
  - spec/gemfiles/52.gemfile
  - spec/gemfiles/60.gemfile
rvm:
  - "2.3"
  - "2.4"
  - "2.5"

matrix:
  exclude:
    - rvm: "2.3"
      gemfile: spec/gemfiles/60.gemfile
      # wwtd isn't smart enough to matrix exclude without specifying all dimensions,
      # so we have to list this here
      env: TEST_DB_USERNAME=postgres
    - rvm: "2.4"
      gemfile: spec/gemfiles/60.gemfile
      env: TEST_DB_USERNAME=postgres

script: bundle exec rake spec

addons:
  postgresql: "9.6"

services:
  - redis-server

before_install:
  - gem update bundler

before_script:
  - psql -c 'create database "inst-jobs-test-1";' -U postgres

env:
  - TEST_DB_USERNAME=postgres
