language: ruby
gemfile:
  - spec/gemfiles/52.gemfile
  - spec/gemfiles/60.gemfile
rvm:
  - "2.6"
  - "2.7"

script: bundle exec rake spec

addons:
  postgresql: "9.6"

services:
  - redis-server

before_install:
  - gem update bundler

before_script:
  - psql -c 'create database "inst-jobs-test-1";' -U postgres

env:
  - TEST_DB_USERNAME=postgres
