language: ruby
gemfile:
  - gemfiles/activerecord_6.0.gemfile
  - gemfiles/activerecord_6.1.gemfile
rvm:
  - "2.6"
  - "2.7"
  - "3.0"

script: bin/rake spec && bin/rubocop

addons:
  postgresql: "9.6"

before_install:
  - gem update bundler

before_script:
  - psql -c 'create database "inst-jobs-test-1";' -U postgres

env:
  - TEST_DB_USERNAME=postgres
